config/routes.rb
Rails.application.routes.draw do
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#welcome'
  get 'auth/facebook/callback' => 'sessions#create'
  get '/about' => 'static_pages#about'
  get '/contacts' => 'static_pages#contacts'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :categories do 
  	resources :products
  end

  resources :carts do 
  	resources :line_items, only: [:index, :show]
  end

  resources :orders
  resources :line_items, only: [:new, :create, :index, :destroy]
  resources :users, only: [:new, :create, :show]

  namespace :admin do 
  	resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

	has_many :line_items
	has_many :products, through: :line_items
	belongs_to :order
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :products
end

app/models/line_item.rb
class LineItem < ApplicationRecord
	
	belongs_to :cart
	belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord

	has_one :cart
end

app/models/product.rb
class Product < ApplicationRecord

	belongs_to :category
	has_many :line_items
	has_many :carts, through: :line_items
end

app/models/session.rb
class Session < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord

	before_save {self.email = email.downcase} #ensures program can hanle mixed case email even if database adapter cannot handle mixed case indexes
	validates :name, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, 
										uniqueness: {case_sensitive: false}
	validates :password, presence: true, length: {minimum: 8}
	has_secure_password
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def front_page
  end

  def welcome
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  	@user = User.new
  end

  def create 
  	@user = User.new(user_params)
  	if @user.save
  		session[:user_id] = @user.id
  		flash[:notice] = "Welcome to Lil's Essential Oils"
  		redirect_to categories_path
  	else 
  		render 'new'
  	end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!!current_user
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LilsEssentialOils</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Help",   '#' %></li>
              <% if logged_in? %>
                <li><%= link_to "Log out", logout_path, method: :delete %></li>  
              <% else %>
                <li><%= link_to "Log in", login_path %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div>
		<div class="alert">
			This form contains <%= pluralize(@user.errors.count, "error") %>
		</div>

		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li> 
			<% end %>
		</ul>
	</div>
<% end %>